### ISSUE TITLE
exemple de serveur de communication

### ISSUE THREAD

**Issue by SebCanet** [zeptoline/ScratchHome#1]
https://github.com/okhiroyuki/Scratio

**Comment by zeptoline** [comment]
Du coup, je me suis inspiré d'un projet qui a déjà été fait entre Scratch et un programme Java (https://github.com/cbecc/scratch4arduino).
Comme on fait la communication directement en Java, le server peut être lancé depuis le plugin, du coup on a plus besoin d'avoir un server entre Scratch et SH3D. 

Au niveau actuel, on peut récupérer les informations de Scratch, mais il faut rentrer soit-même les identifiants des meubles et la couleur. On travaille donc actuellement à automatiser l'écriture de fichier Scratch depuis le plugin.

**Comment by SebCanet** [comment]
Très bonne idée.
Script de départ : https://github.com/damellis/A4S
Par contre s'il est lancé depuis le plugin faites attention à bien surveiller le processus pour éviter qu'il ne rentre en boucle ou bien qu'il reste actif après avoir fermé le plugin ou Sweethome3d, peut être lancer un paneneau de contrôle ?
Et pour lister les objets modifiables, comment faîtes vous vos choix ?

**Comment by zeptoline** [comment]
Nous avons posté une release avec la dernière version du plugin. 
On a donc ajouté un panneau de contrôle (fait en Swing), permettant d'afficher les derniers messages reçus, et de redémarrer le serveur d'écoute.

Et pour l'export en json, on a rajouté une option pour soit sélectionner tous les objets, soit uniquement les lampes. Pour faire cette sélection, il a juste été nécessaire de regarder si l'objet faisait partie d'une certaine classe, qui est utilisé pour tous les objets de type lampe (http://www.sweethome3d.com/javadoc/com/eteks/sweethome3d/model/Light.html). Selon le choix lors de la sélection, différentes couleurs seront disponibles dans Scratch (toutes les couleurs pour tous les objets, seulement jaune et noir pour les lampes).

Matthieu est en train de faire des captures d'écrans du fonctionnement du plugin.

**Comment by SebCanet** [comment]
Excellente progression ! Ca donne envie de voir le reste.
L'export en json impose comme extension de sauvgarde que sb2, ce qui ne convient pas.
Scratch ne se connecte pas au serveur dans mes essais.
Pour le nom de l'extension, gardez juste "ScratchHome" car l nom long actuel "ScratchHome (Scratch with SweetHome3D)" ne rentre pas.

**Comment by zeptoline** [comment]
En fait, Scratch ne sait pas que le serveur est lancé, mais il envoie quand même sur le port donné dans l'extension. Du coup si le serveur est lancé sur SweetHome, il récupérera les messages de Scratch.
Concernant l'export en json, quel format serait souhaitable en plus ? Le sb2 est visiblement le format par convention pour les extensions Scratch.

Sinon, Matthieu est en train de faire un guide d'utilisation, qu'il rajoutera ici avec quelques images, et qu'on copie collera dans la section wiki.

**Comment by SebCanet** [comment]
Quand on lance un sb2, le json est zippé dedans. Hors en sauvegardant en sb2 on 'ouvre' le fichier au lieu de 'l'importer'.
Scratch envoie une requête au serveur et quand il lui répond un en tête correct alors il passe au vert.
L'idéal pour le bloc serait de pouvoir 'allumer/éteindre la lampe'.

**Comment by SebCanet** [comment]
Pouvez vous rajouter après la question 'tous les objets ou seulement les lampes', une question 'un bloc avec menu déroulant' ou bien 'un blo par objet'. Et dans le 2ème seul menu déroulant ur chaque bloc : allumer/éteindre.

**Comment by LordInateur** [comment]
bonjour à tous,
ci-dessous une petite démo d'utilisation du plug-in pour l'utiliser comme il a été pensé :

Une première vue d'une pièce qu'on a fabriqué pour l'occasion :
![screen1_shavant](https://cloud.githubusercontent.com/assets/15981373/13178149/af91a362-d71d-11e5-8a3d-ae818a78ad00.JPG)

Ici vous voyez le déroulé du menu de l'extension qui propose donc de démarrer le serveur et de créer un export sb2 pour interagir avec scratch.
![screen2_menu_scratchhome](https://cloud.githubusercontent.com/assets/15981373/13178147/af90e6f2-d71d-11e5-83f2-b3e40b948af3.jpg)

Nous allons donc commencer par créer le fichier,
ici nous avons donc laissé le choix à l'utilisateur de changer la couleur de tout les objets au lieu de seulement les lampes, ici la question permet de choisir ce qui va être transmis à scratch.
![screen3_choixtoutoulampe](https://cloud.githubusercontent.com/assets/15981373/13178150/af92ce04-d71d-11e5-8aca-4ce259b2d357.jpg)

Puis vient le choix de l'emplacement d'enregistrement du fichier
![screen4_enregistrementfichier](https://cloud.githubusercontent.com/assets/15981373/13178148/af9115e6-d71d-11e5-96c4-82e274cf0805.jpg)

Maintenant il faut importer le fichier dans scratch via "importer d’extension expérimental"
![screen5_importscratch](https://cloud.githubusercontent.com/assets/15981373/13178139/af7ac3ea-d71d-11e5-85f5-ed7686d94554.jpg)

Un nouveau bloc est apparu dans la rubrique "autre blocs" avec la liste des objet transmis
![screen6_prevuescratch](https://cloud.githubusercontent.com/assets/15981373/13178143/af7d835a-d71d-11e5-9ad3-b24b92aac161.jpg)

Et la liste des couleurs prévue. A noter que si seules les lampes sont transmises, seules les couleurs jaune et noir sont disponibles.
![screen7_prevuescratch_couleur](https://cloud.githubusercontent.com/assets/15981373/13178140/af7bae4a-d71d-11e5-9cbd-8e9853b72588.jpg)

Maintenant que le bloc est prêt, il est temps de démarrer le serveur d'écoute sur SweetHome
![screen2_menu_scratchhome](https://cloud.githubusercontent.com/assets/15981373/13178147/af90e6f2-d71d-11e5-83f2-b3e40b948af3.jpg)
![screen8_serveur](https://cloud.githubusercontent.com/assets/15981373/13178141/af7c67ea-d71d-11e5-9592-72533a607c42.JPG)

Maintenant cliquez sur le drapeau vert pour exécuter la requête et admirer le résultat :) 
![screen9_bloc](https://cloud.githubusercontent.com/assets/15981373/13178144/af7d8b0c-d71d-11e5-933e-bf81595fac29.JPG)
![screen10_resultat1](https://cloud.githubusercontent.com/assets/15981373/13178142/af7c68da-d71d-11e5-979f-6e4e94aec57e.jpg)

Modifier maintenant les valeurs à votre guise pour avoir le résultat voulu.
![screen11_bloc2](https://cloud.githubusercontent.com/assets/15981373/13178145/af8c1c94-d71d-11e5-89b5-6002bc6976b8.JPG)
![screen12_resultat2](https://cloud.githubusercontent.com/assets/15981373/13178146/af8ea1f8-d71d-11e5-8807-72efa18dbd3c.jpg)

**Comment by zeptoline** [comment]
J'ai rajouté une nouvelle release

Scratch passe maintenant au vert quand le serveur est lancé.
Si on ne choisi que des lampes, les blocs n'affichent que "allumer" ou "éteindre"

Il faut encore faire le json pour un bloc par objet, et faire l'export en vrai sb2.
