### ISSUE TITLE
internationalisaion

### ISSUE THREAD

**Issue by SebCanet** [zeptoline/ScratchHome#2]
Pouvez vous extraire les chaînes de caractère dans un fichier TXT encodé en UTF8 ? traductions dont le chinois...

**Comment by SebCanet** [comment]
Le créateur de SweetHome le demande aussi : http://www.sweethome3d.com/support/forum/viewthread_thread,6550
A mon avis le plugin devrait : 
1. récupérer la langue en cours,
2. l'utiliser pour afficher le texte du plugin en tapant dans un fichier texte qui contient toutes les chaînes de caractères dans les différentes langues,
3. l'utiliser pour extraire d'un autre ichier texte qui contient toutes les chaînes de caractères dans les différentes langues pour créer le fichier Scratch.

Qu'en pensez vous ?

**Comment by zeptoline** [comment]
Bonjour,
Nous avons déjà extrait toutes les chaînes de caractères dans un fichier .properties. 
Chaque langue a son fichier de langue, nommé comme ceci : language_[langue].properties (ex : language_fr.properties.
Donc il ne faudrait que récupérer la langue de SH3D, ce qui devrait être possible.

Nous sortirons une release avec ses implémentations dès que ce sera fait
