### ISSUE TITLE
méthode globale

### ISSUE THREAD

**Issue by SebCanet** [zeptoline/ScratchHome#4]
L'idée serait de préparer un fichier INI d'extraction pour que le plugin s'y réfère avant d'être lancé avec des infos du style :
- nom de catégorie de meuble à extraire,
- capteur variable ou
- capteur tout ou rien, ou
- actionneur

**Comment by zeptoline** [comment]
J'ai rajouté un fichier qui permet de dire si on veut toujours prendre sous forme de menu, ou si l'on ne veut que les lampes.

Et j'en ai profité pour corriger les problèmes avec les blocs par objets, qui marchent maintenant correctement, ainsi que les couleurs, qui s'affichent toutes bien.
