### ISSUE TITLE
export plan 2D

### ISSUE THREAD

**Issue by SebCanet** [zeptoline/ScratchHome#6]
Exporter automatiquement la vue 2D en SVG pour nourrir l' arrière plan dans le fichier sb2 comprenant ainsi quelques infos par défaut + le JSON.

**Comment by SebCanet** [comment]
ATTENTION à redimensionner en proportionnel en 480x360 maxi.

**Comment by zeptoline** [comment]
Jean-Baptiste s'en est occupé. Je prépare une release 1.5 qui contiendra les changements
