### ISSUE TITLE
Commandes dans menu 'ScratchHome'

### ISSUE THREAD

**Issue by SebCanet** [zeptoline/ScratchHome#9]
Dans le menu ScratchHome une fois le plugin installé dans SweetHome3D, il faudrait remplacer :
- 'Lancer le serveur d'écoute' par 'Lancer le serveur de communication'
- 'Créer un fichier SB2' par 'Générer un fichier Scratch/sb2'

Merci.

**Comment by zeptoline** [comment]
J'ai remplacé dans les fichiers de langues, et je vais faire une release avec quelques autres fix
